version: '3.8'

services:
  backend:
    build:
      context: ./frontend/backend
      dockerfile: Dockerfile
    container_name: asmp_backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/Backend
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: asmp_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
